// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: users.sql

package databases

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  username, 
  full_name,
  email,
  hash_password
) VALUES (
  $1, $2, $3, $4
) RETURNING username, full_name, email, hash_password, created_at, updated_at
`

type CreateUserParams struct {
	Username     string `json:"username"`
	FullName     string `json:"full_name"`
	Email        string `json:"email"`
	HashPassword string `json:"hash_password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.FullName,
		arg.Email,
		arg.HashPassword,
	)
	var i User
	err := row.Scan(
		&i.Username,
		&i.FullName,
		&i.Email,
		&i.HashPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT username, full_name, email, hash_password, created_at, updated_at FROM users 
WHERE username = $1
`

func (q *Queries) GetUser(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, username)
	var i User
	err := row.Scan(
		&i.Username,
		&i.FullName,
		&i.Email,
		&i.HashPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
