DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS games CASCADE;
DROP TABLE IF EXISTS picks;
DROP TYPE IF EXISTS spread_winner;
DROP TYPE IF EXISTS spread_picks;
DROP TYPE IF EXISTS spread_type;
DROP TYPE IF EXISTS season_type;
DROP TYPE IF EXISTS league;